---
title: C28125 | Microsoft Docs
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
caps.latest.revision: 6
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: 96aeeed083375c5432eab3637d1131369742f75a
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 08/22/2018
ms.locfileid: "42632765"
---
# <a name="c28125"></a>C28125
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Bu konuda en son sürümünü şu yolda bulunabilir: [C28125](https://docs.microsoft.com/visualstudio/code-quality/c28125).  
  
Uyarı C28125: işlev gelen bir try / except bloğu içinden çağrılmalıdır  
  
 Sürücü, bir try / except bloğu içinden gibi çağrılmalıdır bir işlev çağırma [ProbeForRead](http://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](http://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](http://msdn.microsoft.com/library/windows/hardware/ff554664.aspx).  
  
## <a name="example"></a>Örnek  
 Aşağıdaki kod örneği bu uyarıyı üretir:  
  
```  
ProbeForRead(addr, len, 4);  
```  
  
 Aşağıdaki kod örneği bu uyarıyı ortadan kaldırır:  
  
```  
  
__try  
{  
    ProbeForRead(addr, len, 4);  
}  
__except(EXCEPTION_EXECUTE_HANDLER)  
{  
    Status = GetExceptionCode();  
    ... report error status  
}  
```



