---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 48f18934d1bf78a1764bd3ac7a7c8b7b64508ece
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 10/07/2019
ms.locfileid: "72017750"
---
# <a name="c6312"></a>C6312
Uyarı C6312: Olası sonsuz döngü: try-except için özel durum filtre ifadesinde sabit EXCEPTION_CONTINUE_EXECUTION kullanımı

 Bu uyarı, yapılandırılmış bir özel durum işleyicisinin filtre ifadesinde `EXCEPTION_CONTINUE_EXECUTION` (ya da-1 ' i değerlendiren başka bir sabit) kullanımını gösterir. @No__t-0 sabit değerinin kullanımı sonsuz bir döngüye neden olabilir. Örneğin, donanım tarafından bir özel durum ortaya çıktığında, özel duruma neden olan yönerge yeniden başlatılır. Özel duruma neden olan adres hala bozuksa, başka bir özel durum oluşur ve aynı şekilde işlenir. Bu, sonsuz bir döngüye neden olur.

 @No__t-0 ' a yönelik açık bir çağrı sonsuz döngüye doğrudan neden olmaz, ancak korunan bloktaki kodu yürütmeye devam eder. Bu beklenmeyen bir yol olabilir ve geçersiz bir işaretçinin başvurusunu kaldırmak için `RaiseException` kullanılmışsa sonsuz döngüye neden olabilir.

 Genellikle, `EXCEPTION_CONTINUE_EXECUTION` yalnızca filtre ifadesinde çağrılan bir işlev tarafından döndürülmelidir, bu da özel duruma veya temeldeki belleğe neden olan işaretçiyi çözme şansı vardır.

## <a name="example"></a>Örnek
 Aşağıdaki kod bu uyarıyı oluşturur:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Bu uyarıyı düzeltmek için aşağıdaki kodu kullanın:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```