---
title: C6320 | Microsoft Docs
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C6320
helpviewer_keywords: C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: "10"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload: multiple
ms.openlocfilehash: dbf498f943fb4f6e446cd254e7ca5f844ee0ec68
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 12/22/2017
---
# <a name="c6320"></a>C6320
C6320 Uyarı: özel durum filtresi ifadesidir sabit exceptıon_execute_handler. Bu işlenecek amaçlanmamıştır özel durumlar maskeleyebilir  
  
 Bu uyarı yan etkisi, blok __except exceptıon_execute_handler sabiti kullanarak gösterir. Bu durumda, deyiminde \__except blok istediğiniz belirli bir işlev işlemek için özel durumlar dahil olmak üzere özel durum işleme için her zaman yürütülecek. Bu işleme önce özel durum gözden geçirmeniz önerilir.  
  
## <a name="example"></a>Örnek  
 Aşağıdaki kod, __except engellemesi nedeniyle bu uyarı oluşturur. her türlü özel durumları işleme deneyin:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Bu uyarı düzeltmek için `GetExceptionCode` aşağıdaki kodda gösterildiği gibi işleme önce belirli bir özel durum denetlemek için:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Ayrıca Bkz.  
 [try-except Deyimi](/cpp/cpp/try-except-statement)